function hFig = createFigure(figureTitle,position)
% createFigure Create a hidden white figure with consistent defaults.
if ~exist('position','var') || isempty(position)
    position = [100 100 1500 950];
end

hFig = figure( ...
    'Visible','off', ...
    'Color','w', ...
    'Name',figureTitle, ...
    'Position',position);
end
